### ISSUE TITLE
Is there an online link for node module?

### ISSUE THREAD

**Issue by vydingding** [kaizensoze/node-github#110]
I would like to use it for node modules in var Client, to use for a heroku app deployed online. Is there any link for the module?

Ex: var Client = require("C:/Users/ACER Aspire/Thesis/node-js-getting-started/node_modules/github4/lib");, but this time an online link.

**Comment by kaizensoze** [comment]
There is not. You can't use npm with the heroku app? (I might be misunderstanding the question.)

**Comment by vydingding** [comment]
My project makes heroku links execute node commands. While I can do it locally, when I try to do it online, it just says internal server error.

**Comment by kaizensoze** [comment]
Ok I mean you could always just host it somewhere. I don't have any plans to host it anywhere other than npm though.
