### ISSUE TITLE
Is there any command to get sha blob of a file?

### ISSUE THREAD

**Issue by vydingding** [kaizensoze/node-github#111]
I want to update a file but I need to constantly change it's SHA in my node js code. Is there any command to get sha blob through .getSha or something?

**Comment by kaizensoze** [comment]
Would getBlob help?

https://kaizensoze.github.io/node-github/#api-gitdata-getBlob

**Comment by vydingding** [comment]
But it still requires a previous sha. And I know getContent gives the sha, but it doesn't give it separately; it gives out ALL the contents of the file including the sha.

**Comment by kaizensoze** [comment]
Right. I don't know of a getSha, but you can double check the github api doc: https://developer.github.com/v3/.
