### ISSUE TITLE
Future of node-github

### ISSUE THREAD

**Issue by stefanwalther** [kaizensoze/node-github#113]
Hi,

I am following this branch of mikedeboer/node-github for quite a while and I am wondering if there is a plan to either merge again or to spin off completely?

Good work, thx a lot for all your efforts @kaizensoze 

Regards
Stefan

**Comment by kaizensoze** [comment]
Ideally I'd like to merge the fork into mikedeboer/node-github and become a maintainer, which might become a reality:

https://github.com/mikedeboer/node-github/issues/302#issuecomment-222128951

**Comment by kaizensoze** [comment]
I've been made maintainer of the upstream so I'll be merging this fork when I get a chance and marking it DEPRECATED.

**Comment by stefanwalther** [comment]
Great news!
