### ISSUE TITLE
A method to get repo contents and name

### ISSUE THREAD

**Issue by vydingding** [kaizensoze/node-github#116]
Is there a method where we can get repo contents and their names? I want to do a for loop that checks my google docs, and if a filename is not on the spreadsheet, it deletes it from the repo.

**Comment by kaizensoze** [comment]
So a list of repos and filenames in each repo? You'd have to do at least two calls:

https://developer.github.com/v3/repos/#list-your-repositories
https://developer.github.com/v3/git/trees/

Btw, this repo has been merged into upstream and is now deprecated. Use [mikedeboer/node-github](https://github.com/mikedeboer/node-github) instead.

**Comment by vydingding** [comment]
Mikedeboer is very similar to this one, right?

Also, just a list of filenames in each repo. Is there like a repos.get something command?

**Comment by kaizensoze** [comment]
Yes, `kaizensoze/node-github` was forked from `mikedeboer/node-github`. 

It's in the documentation: https://kaizensoze.github.io/node-github/#api-repos-getAll. And then https://kaizensoze.github.io/node-github/#api-gitdata-getTree to get filenames.

If anything is missing you can file a ticket at `mikedeboer/node-github`. I'm going to close this one.
