### ISSUE TITLE
getContent of a directory

### ISSUE THREAD

**Issue by vydingding** [kaizensoze/node-github#117]
I try to getContent this but it gives me a 400 "Bad Request" error.          

user: "vydingding",
          repo: "vydingding.github.io",
          path: "_data/"
          }

How do we get contents of a certain directory?

**Comment by kaizensoze** [comment]
Try without the slash, so just "_data".

**Comment by vydingding** [comment]
Got it! Ashamed I even asked for that. Is there any way to access the files in that directory in an array manner?
