### ISSUE TITLE
why github4 as repo/project name?

### ISSUE THREAD

**Issue by mikemimik** [kaizensoze/node-github#14]
I'm just curious as to why the number 4 was added to the repo/project name? Is there some significance to this?

I only ask because I am one of those random people with some spectrum of OCD about stuff like that. I was also using the node-github repo until I've now found it's probably dead.

I'm glad for all the changes you've made. I'll be moving over to this repo in the next few days when I have time to work on my project requiring it.

**Comment by kaizensoze** [comment]
Yeah so `node-github` was an original published name that the author of `github` never removed. I think there was even a ticket in the old repo asking to remove that. Then someone forked the `github` repo as `github2` and then `github3` was taken so I just went with `github4`.

As for changing the repo, I figured it'd be best to match the npm module name.

Any suggestions for a name that's not already taken in npm?

**Comment by mikemimik** [comment]
`github-main` is not taken on npm.

I wouldn't mind `github-official` but I'm not sure that's appropriate or allowed.

To my knowledge the github repo name and the npm package name can be different. Perhaps start with a different github repo name, and then sort out the npm package name at a later date as it's not really of high importance at this stage.

Other suggestions would be welcome.

**Comment by kaizensoze** [comment]
If enough people complain I'll change it.

**Comment by kaizensoze** [comment]
I changed the repo name back to node-github and away from the more opaque github4.
