### ISSUE TITLE
Repl and docs improvement ideas

### ISSUE THREAD

**Issue by reactima** [kaizensoze/node-github#31]
Hi, thank you for taking care of node-github.

Here's few ideas from Ramda.js how to improve github4 and probably build something very useful:
#1 Repl

http://ramdajs.com/repl/?v=0.19.0
https://github.com/hemanth/ramda-repl
#2 Add search input filter to Doc

http://ramdajs.com/0.19.0/docs/
#3 Quick jump from Docs to Source Code, Repl

https://github.com/ramda/ramda/blob/v0.19.0/src/add.js
#4 Here's a good example of REST Api Console

https://apigee.com/console/linkedin?apig_cc=1

It's kind of natural to see confirmation of your API research before doing actually coding or using wrapping library. If you understand the end result quickly, it's natural to start using and trusting wrapping library. 

For example, 
## Please compare Docs 

misc
misc - emojis
## With output

https://developer.github.com/v3/emojis/
## GET /emojis

Status: 200 OK
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
{
  "+1": "https://github.global.ssl.fastly.net/images/icons/emoji/+1.png?v5",
  "-1": "https://github.global.ssl.fastly.net/images/icons/emoji/-1.png?v5",
  "100": "https://github.global.ssl.fastly.net/images/icons/emoji/100.png?v5",
  "1234": "https://github.global.ssl.fastly.net/images/icons/emoji/1234.png?v5",
  "8ball": "https://github.global.ssl.fastly.net/images/icons/emoji/8ball.png?v5",
  "a": "https://github.global.ssl.fastly.net/images/icons/emoji/a.png?v5",
  "ab": "https://github.global.ssl.fastly.net/images/icons/emoji/ab.png?v5"
## }

Hope the above info is useful.

P.s. I wish I can revisit this issue in few month and probably prototype something or send PR.

**Comment by kaizensoze** [comment]
Thanks I'll have to see what Ramda.js is using for doc generation. Right now I'm just using apidoc, but might switch to jsdoc.

**Comment by kaizensoze** [comment]
Those ramda.js doc features aren't really compatible with the existing apidoc and I have a ticket for possibly switching over to jsdoc which might allow for additional functionality so I'm going to close this for now.
