### ISSUE TITLE
github issues api seems to return nothing 

### ISSUE THREAD

**Issue by jgw96** [kaizensoze/node-github#50]
If i call github.issues.getForRepo or github.issues.getForUser(after authenticating) it returns nothing but an object about rate limits for the github api. It does not return any other data. Im using Node 5.1.1 on a macbook pro running 10.11 El Capitan.

Example of returned object when calling these two methods: 
    [ meta: { 'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4995',
    'x-ratelimit-reset': '1451887812',
    etag: '"a9cd6a41628c101c988f29e6ec85aa89"',
    status: '200 OK' } ]

**Comment by jgw96** [comment]
This is the specific piece of code that im using. 

``` javascript
github.issues.getForRepo({
        user: req.body.username,
        repo: req.body.repo
    }, (err, res) => {
        if (err) {
            console.log(err);
        }
        else {
            console.log(res);
            res.id = "issues";

            store.add(res, (err) => {
                if (err) {
                    console.log(err);
                }
            })
        }
    })
```

**Comment by kaizensoze** [comment]
I just pushed an example with that method. Seems to be working. 

``` javascript
"use strict";

var Client = require("./../index");
var testAuth = require("./../test_auth.json");

var github = new Client({
    debug: true
});

github.authenticate({
    type: "oauth",
    token: testAuth["token"]
});

github.issues.getForRepo({
    "user": "kaizensoze",
    "repo": "node-github"
}, function(err, res) {
    console.log(err, res);
});

```

What's your code for initializing the object and authenticating?

EDIT: Also, does the authenticated user have access to the repo?
