### ISSUE TITLE
errors.js is basically useless

### ISSUE THREAD

**Issue by mikemimik** [kaizensoze/node-github#79]
The statusCodes and errors don't mean anything while in use. `err.toJSON()` for example always returns an object with a `status` property that is always `undefined`.

I will create a PR with some changes for this when I have a chance, for now just putting this here so I remember.

**Comment by kaizensoze** [comment]
Aye, I haven't even touched that file since the fork. Pull request welcome!

**Comment by kaizensoze** [comment]
HttpError status is no longer undefined.
