### ISSUE TITLE
none of the docs mention callback utilization

### ISSUE THREAD

**Issue by mikemimik** [kaizensoze/node-github#80]
`/doc` and `https://kaizensoze.github.io/node-github` don't mention anything about callbacks. Is there a way to incorporate this?

**Comment by mikemimik** [comment]
I notice that `https://github.com/kaizensoze/node-github/wiki/Transition-from-upstream` mentions revamping docs.

You can close this issue or keep it open as a reminder.

**Comment by kaizensoze** [comment]
Yeah that could definitely use a pull request. I've already revamped the docs relative to upstream but it could certainly use some more info like callbacks. I went ahead and removed the next steps section in the wiki so it's really just whatever issues are open as far as things that need to be done.

**Comment by kaizensoze** [comment]
I went ahead and removed the next steps section in the wiki so it's really just whatever issues are open as far as things that need to be done.
