### ISSUE TITLE
Entry point is broken

### ISSUE THREAD

**Issue by drinchev** [kaizensoze/node-github#90]
Moving all files to `/lib` broke the `entry` point in `package.json`

Cause :  https://github.com/kaizensoze/node-github/commit/0d07c1b8ebde60213083a1a8877c715ff7c63d5f

Solution : https://github.com/kaizensoze/node-github/pull/89

**Comment by kaizensoze** [comment]
Sorry about that. Pushed fix in 0.5.3.
