### ISSUE TITLE
Access header information from error callback

### ISSUE THREAD

**Issue by cbargren** [kaizensoze/node-github#91]
It would be nice if there was a way to access the header information for a failure in the error callback. This is helpful for checking the scope of the token that was used to make a request so you can inform the user if they need new permissions. I have a way to do that [here](https://github.com/cbargren/node-github/commit/6b2092ac96d1ba10cfc4adc51cb6f035aee98205), but the fix is a little janky and there might be a better long-term solution. I can fix this up and PR it if you would like, though.

**Comment by kaizensoze** [comment]
Sure, I'll add it now.
